spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: jdbc:postgresql://localhost:5432/notezen?currentSchema=notezen
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5432/notezen?currentSchema=notezen
    locations: classpath:db/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}