server:
  port: 8083
  servlet:
    context-path: /api/v1
spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/notezen?currentSchema=notezen
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

jwt:
  secret: 2b44b0b00fd822d8ce753e54dac3dc4e06c2725f7db930f3b9924468b53194dbccdbe23d7baa5ef5fbc414ca4b2e64700bad60c5a7c45eaba56880985582fba4
  expiration: 36000000
  issuer: anipeptun
#
