spring:
  config:
    activate:
      on-profile: "dev"

  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/notezen?currentSchema=notezen
    username: postgres
    password: 123
  flyway:
    url: jdbc:postgresql://localhost:5432/notezen?currentSchema=notezen
    locations: classpath:db/migration
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}